### PR TITLE
Remove references to pre-compiled layouts across all apps (#98)

### LINKED ISSUE #98: Remove all references to pre-compiled template files
template files ( \*.ui ) are compiled by pyuic to ui_\*.py files via the Makefile
These files must be generated during the build process, and not be stored in the repo, so git has been configured to ignore files that match ui_*.py
But, a lot of Apps use compiled templates that do not start with 'ui_' , and were compiled outside of the makefile. The references in these apps need to be updated, and pre-compiled templates untracked.

### PR DESCRIPTION
**Pull request by jithinbp**
Fixes #98 
- Multiple files deleted

### CODE REVIEW

**Comment by jithinbp** [comment]
Build failed with missing PyQt4 dependency even though PyQt4 seems to have installed okay via apt-get . Which obviously means that the travis build passed previously because pyuic4 was not being invoked due to ui\_*.py files already being a part of the repository and up to date. They've now been removed.

Is it essential for packages to be installed from source for travis to work? I can see that PyQt4, Sip etc have been installed from source. @wavicles 
```
Setting up python-qt4 (4.9.1-2ubuntu1) ...
Setting up pyqt4-dev-tools (4.9.1-2ubuntu1) ...
Processing triggers for libc-bin ...
ldconfig deferred processing now taking place    0.31s

$ make
compiling UI : PSL_Apps/utilityApps/templates/ui_testing.py
Traceback (most recent call last):
  File "/usr/bin/pyuic4", line 3, in <module>
    import PyQt4.uic.pyuic
ImportError: No module named 'PyQt4'
make: *** [PSL_Apps/utilityApps/templates/ui_testing.py] Error 1

The command "make" failed and exited with 2 during .

Your build has been stopped.
```

**Comment by viveksb007** [comment]
@jithinbp travis build is failing. Seems like some error in utilityClass.py https://travis-ci.org/fossasia/pslab-desktop-apps/jobs/230267282#L1140
Could you have a look at it?

**Comment by jithinbp** [comment]
Added a framework for creating help files in markdown format. Screenshots : 
### An example of an experiment's help page generated with the following markdown
```
---
layout: expt
title: Astable Multivibrator
date: 2017-05-21
description: Multivibrator circuit using a pair of transistors
imagebase: astable-multivibrator
---


### Sine wave plot example
--------------------------

~~~python
from pylab import *
import numpy as np
x=np.linspace(0,2*np.pi,100)
plot(x,np.sine(x))
show()
~~~


```
jekyll_a

A responsive slide out menu with a table of contents is also included. The list is auto-generated from all the markdown files present in the _apps/ and _utilities/ directories.

jekyll_b

**Comment by jithinbp** [comment]
python-pslab needs to be fixed before travis build can pass.  its setup.py explicitly invokes python3, and this causes a missing dependency error while installing it here.

**Comment by mariobehling** [comment]
@jithinbp Ok, thanks. Merging it. Please fix in following commits.

**Pull request merged**
