### PR TITLE
Old style exceptions --> new style for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
Old style exceptions are syntax errors in Python 3 while new style exceptions work as expected in both Python 2 and Python 3.

### CODE REVIEW

**Comment by CloudyPadmal** [comment]
Hello @cclauss ! #214 contain these changes as well. May be there was some branching issue? We can close this PR and merge #214 , can we?

**Comment by cclauss** [comment]
Please merge the PR that you are most comfortable with and then after that is done, I can rebase the other to verify that all changes are properly in place.  Some projects are happy to get all fixes in a single PR like #214 while other projects want PRs that focus on resolving a single problem like this PR does.  The approach of delivering two PRs gives you the choice of taking the road that is most comfortable to this project .

**Comment by cclauss** [comment]
Closing because __Files changed 0__ now that #214 has been merged.

**Comment by CloudyPadmal** [comment]
Great! In FOSSASIA projects we go for a practice where one PR solves one issue. Thanks!

**Comment by cclauss** [comment]
LOL!  Yes but... that was not the road taken in this case.  ;-)  All is well that ends well.  🙏

**Pull request closed without merging**
