### PR TITLE
Documentation added for NJ_FET , Diode IV apps

### PR DESCRIPTION
**Pull request by jithinbp**
Issues : 
- Write md documentation for diode_IV app #108 
- Write md documentation for N-Channel FET app #109 
- Create a /docs/ folder and move all documentation there #107 . add screenshots #102 

Rebasing has been tried , but unsuccessfully. After merging the previous PR, the HEAD should have been level with fossasia/pslab-desktop-apps/development, but that wasn't the case, even though git diff was 0.
This PR has commits belonging to previously merged PRs, but the list of files changed only pertain to the latest changes.

### CODE REVIEW

**Comment by viveksb007** [comment]
@jithinbp there are build errors because setuptools can't be imported. 
I think there should be a command in travis to install ```python3-setuptools``` first. 
Like ```apt-get install python3-setuptools```. I ran into same error when installing locally.
About reflection of previous commits, when you sent PR previously commits in that PR were squashed into a single commit. So your original commits are unique although your​ change in codebase is done. So next time when you send a PR those commits come again.
To solve this I create a branch from master lets call it dev and do changes in it and send a PR suppose it has 4 commits. In remote master branch those 4 commits are squashed into 1 commit. Now my 4 commits are unique and would be reflected again in next PR. So delete current dev branch. Pull changes in master branch and from there create another branch which would have that single squashed commit and not you 4 unique commits.
Hopefully its clear now.

**Comment by jithinbp** [comment]
The build errors are because of pslab-python's makefile.
They were present in the last two PRs also, after PSlab-python was added as
a dependency.
I'll take care of it

**Comment by jithinbp** [comment]
Thank you for your help with handling the unique commits. I'll try this
approach.

Does this also mean that I have to delete my branch and start over each
time a squash+commit is used for merging a PR?

**Comment by viveksb007** [comment]
Yes, after each squash + commit on remote branch, you need to delete you current branch.
You pull squashed changes from remote branch to your local main branch. Create another branch and solve issue from there.
There might be some other way to handle this.

**Comment by jithinbp** [comment]
@viveksb007 I've been all over SO, but can't seem to find a better way than what you've mentioned. Can you approve the PR so that the current work can be merged? then I'll delete my branch and start afresh
thanks

**Comment by viveksb007** [comment]
It can't be merged yet, travis​ build has to be passed for us to merge the PR.
Mario has higher permission, he can merge it.

**Comment by CloudyPadmal** [comment]
So @viveksb007 to pull from master branch we need to merge these existing commits right?

**Comment by jithinbp** [comment]
@viveksb007 I have the option to 'Squash and merge' , but I'd rather wait for Mario.
In the meantime, I'm fixing pslab-python's makefile which is responsible for the broken build anyway

**Comment by viveksb007** [comment]
@CloudyPadmal yes first these existing commits needs to be merged. If they are squashed and merged, then all of them would be squashed to single commit and added to development branch in this case. Then you pull those changes from remote branch to a branch in which these commits aren't there. Then continue with another issue.

**Comment by jithinbp** [comment]
@viveksb007 Ideally, if I only add a small number of precise commits, Mario won't have to use 'squash and merge' , so I can continue working without destroying my branch each time.  Can you approve [PR 69 in pslab-python](https://github.com/fossasia/pslab-python/pull/69), so that I can check the travis build here?

**Comment by viveksb007** [comment]
Yes if there are small meaningful commits we can merge your​ branch with main remote branch then original commits are saved. Then we don't have to delete our branch because commits won't be duplicated.

**Comment by jithinbp** [comment]
@CloudyPadmal So the build failed again for all three python versions, despite pslab-python dependency install command running fine this time. desktop-apps couldn't find the PSL module
```
from PSL.commands_proto import applySIPrefix
ImportError: No module named 'PSL'
```
The makefile ran without a problem on my local machine, and the library is correctly detected.
In the travis build logs, the library is installed to /usr/lib/Python2.7/dist-packages/PSL/ for all python versions. There is no explicit mention of Python2.7 anywhere in the Makefile or Setup.py . Grep says there's one in docs/conf.py, but that should not be relevant here.

The other dependencies install to the following location
```
cp -f /builds/PyQt-x11-gpl-4.11.3/pyuic/uic/icon_cache.py /home/travis/virtualenv/python3.3.6/lib/python3.3/site-packages/PyQt4/uic/icon_cache.py
```
while this one tries to enforce debian style paths, and installs in the following way
```
copying build/lib.linux-x86_64-2.7/PSL/SENSORS/BMP180.py -> /usr/lib/python2.7/dist-packages/PSL/SENSORS
```
which probably breaks the virtualenv rules, because the referenced path is outside.
I'll try to amend the Makefile to play nice with the virtualenv.

**Pull request merged**
