### PR TITLE
Add Jekyll framework for creating experiment helpfiles from markdown files

### PR DESCRIPTION
**Pull request by jithinbp**
Issue  #103 
Help files for the various apps can now be auto-generated from small markdown files using Jekyll.
The flexibility allows the user to easily navigate between various help-files via the auto-generated menus

psl_help1

psl_help

jekyll_b

The framework uses css styling from Bootstrap.  I have also included stylesheets for syntax highlighting code snippets.

sample helpfile in markdown form:
```
---
layout: expt
title: AC and DC
date: 2017-05-28
description: Study the difference between AC and DC circuits
---

## Measure the voltage of a dry cell
![](images/schematics/acdc1.svg ){: width="300px"}

Make the connections as shown in the figure. Use a common dry cell battery<br>
Note the values shown by the voltmeter for CH1 . Also observe, that the graph for CH1 is a straight line. This is because the voltage is constant.
```

### CODE REVIEW

**Comment by mariobehling** [comment]
What do you plan to do with Jekyll? Looks like you want to host the app and the website on one repo?

Our standard documentation set up is usually:
1. Add the most important info into the Readme.md
2. Add all other documents into the /docs folder
3. Use yaydoc to generate a static site (Our yaydoc team can do it.).

Yaydoc has some advantages, e.g. search. Please simply place the md files into the docs folder. No need for Jekyll itself.

**Comment by jithinbp** [comment]
All the docs prepared previously for each app were standalone HTML snippets with no cross references to any other utilities that a user might want to look up.
e.g. the current limits of the waveform generator, or the pinout diagram of the expansion slot.

Using a Jekyll template allows putting all essential links across all pages while keeping the actual source plain and simple.

Yaydoc's pure js search feature sounds good.

I have doubts:
 - The App specific HTML files are referenced by the Desktop app which looks for them in /usr/share/pslab/psl_res/    .    Should I let them stay where they are and make a copy in /doc/ until the Yaydoc generator is ready?
Because otherwise the desktop app's help feature will remain broken until the correct HTML path is configured.

**Comment by jithinbp** [comment]
@mariobehling  I have moved a large chunk of documentation to /docs/
While there exists /docs/images/ , I will use the following tree structure for clarity
- docs
  - images
  - apps
     images
  - utilities
      images

The old HTML directory located at psl_res/HTML/ has been left untouched so that the app is still usable while this is being developed. It can be deleted later

**Comment by mariobehling** [comment]
> Using a Jekyll template allows putting all essential links across all pages while keeping the actual source plain and simple.

Same with yaydoc. Just keep link the md-files as you would do in Jekyll.

> The App specific HTML files are referenced by the Desktop app which looks for them in /usr/share/pslab/psl_res/ . Should I let them stay where they are and make a copy in /doc/ until the Yaydoc generator is ready?
Because otherwise the desktop app's help feature will remain broken until the correct HTML path is configured.

Maybe simply set the link to pslab.fossasia.org for now and we will generate the help/documentation in a subfolder here once ready.

**Comment by mariobehling** [comment]
I am unclear why there needs to be different image folders. One image folder should be fine.

**Comment by jithinbp** [comment]
@mariobehling  oh no. I forgot to git add. 
fixed now.
Sorry

**Comment by mariobehling** [comment]
Ok, I am merging this. Please continue following this approach. Cheers.

**Comment by jithinbp** [comment]
terrific. thanks.

**Pull request merged**
